# -*- mode: outline; indent-tabs-mode: nil -*-
version: "3.3"
services:
    grafana:
        image: grafana/grafana
        ports:
        - "127.0.0.1:3000:3000"
        volumes:
        - ./grafana/mounts/etc/grafana:/etc/grafana
    graphite:
        image: graphiteapp/graphite-statsd
        ports:
        - "127.0.0.1:80:80"
    snmp_profiler:
        image: erlang:18.3.4.11
        ports:
        - "21312:21312"
        volumes:
        - .:/app
        command: tail -F a-nonexistent-file
