---
name: "pre-release"

on:
  push:
    branches:
      - "master"

jobs:
  pre-release:
    name: "Pre Release"
    runs-on: "ubuntu-18.04"

    steps:
      - uses: actions/checkout@v2.0.0
      - name: "Get Erlang"
        uses: gleam-lang/setup-erlang@v1.1.3
        with:
          # note: the erl version needs to be available at
          # https://packages.erlang-solutions.com/erlang/debian/pool
          # named like esl-erlang_$VERSION-1~ubuntu~$RELEASE\_amd64.deb
          # where RELEASE is figured out from the distro. Erlang 18
          # is only built for older ubuntu's, which is why this uses 18.04.
          otp-version: "18.3.4.11"
      - name: "Build"
        run: ./compile.sh
      - name: "Package"
        run: tar czf snmp-profiler-${{github.sha}}.tar.gz --transform 's,^,snmp-profiler-${{github.sha}}/,' *
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: |
            *.tar.gz
