---
name: "tagged-release"

on:
  push:
    tags:
      - "*"

jobs:
  tagged-release:
    name: "Tagged Release"
    runs-on: "ubuntu-18.04"

    steps:
      - uses: actions/checkout@v2.0.0
      - name: "Get Erlang"
        uses: gleam-lang/setup-erlang@v1.1.3
        with:
          # note: the erl version needs to be available at
          # https://packages.erlang-solutions.com/erlang/debian/pool
          # named like esl-erlang_$VERSION-1~ubuntu~$RELEASE\_amd64.deb
          # where RELEASE is figured out from the distro. Erlang 18
          # is only built for older ubuntu's, which is why this uses 18.04.
          otp-version: "18.3.4.11"
      - name: "Build"
        run: ./compile.sh && tar czf snmp-profiler.tar.gz *
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            *.tar.gz
